
/gate/geometry/setMaterialDatabase    ./GateMaterials.db


#=====================================================
# GEOMETRY
#=====================================================
/gate/world/geometry/setXLength         400.0 cm
/gate/world/geometry/setYLength         400.0 cm
/gate/world/geometry/setZLength         400.0 cm

/gate/world/daughters/name            OpticalSystem
/gate/world/daughters/insert          box
/gate/OpticalSystem/geometry/setXLength         400.0 cm
/gate/OpticalSystem/geometry/setYLength         400.0 cm
/gate/OpticalSystem/geometry/setZLength         400.0 cm
/gate/OpticalSystem/setMaterial                 Air

/gate/OpticalSystem/daughters/name            crystal
/gate/OpticalSystem/daughters/insert          box
/gate/crystal/placement/setTranslation    0.0 0.0 0.0 mm
/gate/crystal/geometry/setXLength         30.0 mm
/gate/crystal/geometry/setYLength         30.0 mm
/gate/crystal/geometry/setZLength         30.0 mm
/gate/crystal/setMaterial                 LYSO

/gate/systems/OpticalSystem/crystal/attach   crystal

/gate/crystal/attachCrystalSD





#=====================================================
# PHYSICS
#=====================================================
/gate/physics/addProcess PhotoElectric
/gate/physics/processes/PhotoElectric/setModel StandardModel


/gate/physics/addProcess Compton
/gate/physics/processes/Compton/setModel StandardModel


/gate/physics/addProcess RayleighScattering
/gate/physics/processes/RayleighScattering/setModel PenelopeModel


/gate/physics/addProcess ElectronIonisation
/gate/physics/processes/ElectronIonisation/setModel StandardModel e-

/gate/physics/processes/ElectronIonisation/setModel StandardModel e+


/gate/physics/addProcess Bremsstrahlung
/gate/physics/processes/Bremsstrahlung/setModel StandardModel e-

/gate/physics/processes/Bremsstrahlung/setModel StandardModel e+


/gate/physics/addProcess eMultipleScattering e+

/gate/physics/addProcess eMultipleScattering e-

/gate/physics/processList Enabled
/gate/physics/processList Initialized


#=====================================================
# INITIALISATION
#=====================================================
/gate/run/initialize

#=====================================================
# SURFACES
#=====================================================


#=====================================================
# DIGITIZER
#=====================================================
/gate/digitizer/Singles/insert opticaladder

/gate/digitizer/Singles/insert readout
/gate/digitizer/Singles/readout/setDepth  1

#=====================================================
# SOURCE
#=====================================================
/gate/source/addSource sphere_source
/gate/source/sphere_source/gps/type Volume
/gate/source/sphere_source/gps/shape Sphere
/gate/source/sphere_source/gps/radius 0.1 mm 

# Placement
/gate/source/sphere_source/gps/centre 150.0 0.0 0.0 mm 
/gate/source/sphere_source/gps/particle gamma 
/gate/source/sphere_source/gps/monoenergy 511 keV

/gate/source/sphere_source/setActivity 1000 becquerel
/gate/source/sphere_source/gps/angtype iso
/gate/source/sphere_source/gps/mintheta 90 deg 
/gate/source/sphere_source/gps/maxtheta 90 deg
/gate/source/sphere_source/gps/minphi   0 deg
/gate/source/sphere_source/gps/maxphi   0 deg


/gate/source/list


#=====================================================
# PARAMETER
#=====================================================
/gate/random/setEngineName MersenneTwister
/gate/random/setEngineSeed auto

/gate/output/root/enable
/gate/output/root/setFileName optical
/gate/output/root/setRootHitFlag 1
/gate/output/root/setRootSinglesFlag 1



/gate/application/setTotalNumberOfPrimaries 1000001
/gate/application/start




